name: chat_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"  # Supports Dart SDK versions 2.12.0 to 3.x.x and above

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^1.0.0
  emoji_picker_flutter: ^4.3.0
  shared_preferences: ^2.3.2
  camera: ^0.10.5+2
  path_provider: ^2.1.2
  path: ^1.8.3
  video_player: ^2.5.0
  socket_io_client: ^2.0.3+1
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  cloud_firestore: ^5.6.7
  flutter_otp_text_field: ^1.5.1+1
  image_picker: ^1.1.2
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
