// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB83TKCJY6V-mNoVBkCtaThGAQiR-OIrW0',
    appId: '1:103185251185:web:3fe44444d61c00cceb94d0',
    messagingSenderId: '103185251185',
    projectId: 'chatapp-e02c2',
    authDomain: 'chatapp-e02c2.firebaseapp.com',
    storageBucket: 'chatapp-e02c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW4qI0mIyKlmXvxbj4PehxZYrEEnpebYY',
    appId: '1:103185251185:android:97814d8eaf0f5b03eb94d0',
    messagingSenderId: '103185251185',
    projectId: 'chatapp-e02c2',
    storageBucket: 'chatapp-e02c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbNI5QjghObdGMJ4ueLVVDljm-r_0VriI',
    appId: '1:103185251185:ios:0ab3b342969a8a27eb94d0',
    messagingSenderId: '103185251185',
    projectId: 'chatapp-e02c2',
    storageBucket: 'chatapp-e02c2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbNI5QjghObdGMJ4ueLVVDljm-r_0VriI',
    appId: '1:103185251185:ios:0ab3b342969a8a27eb94d0',
    messagingSenderId: '103185251185',
    projectId: 'chatapp-e02c2',
    storageBucket: 'chatapp-e02c2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB83TKCJY6V-mNoVBkCtaThGAQiR-OIrW0',
    appId: '1:103185251185:web:62e2e057a01673adeb94d0',
    messagingSenderId: '103185251185',
    projectId: 'chatapp-e02c2',
    authDomain: 'chatapp-e02c2.firebaseapp.com',
    storageBucket: 'chatapp-e02c2.firebasestorage.app',
  );
}
